sonar.projectKey=yy-framework_view_400cef87-0887-4323-8413-c07f07bf4b90
sonar.qualitygate.wait=true
sonar.host.url=http://114.55.226.181:9002
sonar.login=sqp_6d54c6a690fb7b79ba21b5e1afd46f204b1601fa
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/public/**
sonar.sourceEncoding=UTF-8
